#!/usr/bin/env ruby

require "report_sanity_checker"
require "widget_sanity_checker"

# assuming running from vmdb directory
require File.expand_path('config/environment', ENV["RAILS_ROOT"] || Dir.pwd)
require_relative "../lib/report_sanity_checker/monkey_patch"

if ARGV.include?("-w")
  WidgetSanityChecker.run(ARGV)
else
  ReportSanityChecker.run(ARGV)
end
